name: run checkmarx 



jobs:
  run_ckx_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

        # CX scan
      - name: Checkmarx AST scan
        uses: checkmarx/ast-github-action@main
        with:
          project_name: Testing_JavaVulnerableLab
          branch: development
          base_uri: https://eu.iam.checkmarx.net/
          cx_tenant: alpicloud
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params:  --debug  --debug
